### ISSUE TITLE
The result of fiery static

### ISSUE THREAD

**Issue by DFLyan** [wayveai/fiery#32]
If I want to get the result of Fiery Static of Setting2 in Table I of your paper, should I use the config in "configs/single_timeframe.yml"? When I train the network using this config file from scratch, the IOU is 39.2 when I use the "evaluate.py". However, in the paper, the result is 35.8. Is there another parameter needed to be modified, when I want the network to be one frame as input and the segmentation result of the present frame as output?

**Comment by anthonyhu** [comment]
Hi,

If you want to reproduce the results of FIERY Static in the lift-splat-shoot evaluation setting, you should train the config https://github.com/wayveai/fiery/blob/master/fiery/configs/literature/static_lss_setting.yml

The `configs/single_timeframe.yml` config additionally masks vehicle labels that are not visible from the camera, which is why the IoU is larger. This masking was not present in the original lift-splat-shoot evaluation, so for a fairer comparison it was removed.

**Comment by DFLyan** [comment]
OK, thanks!
